language: bash

os:
   - linux
   - osx

sudo: required

install:
   - "git config --global user.email 'myemail@testplace.com'"
   - "git config --global user.name 'Test User'"

script:
   - "tests/test.sh"
