language: bash

os:
   - linux
   - osx

sudo: required

install:
   - "git config --global user.email 'myemail@testplace.com'"
   - "git config --global user.name 'Test User'"

script:
   - "tests/dest_repo_doesnt_exist.sh && tests/dest_repo_exists_bare.sh && tests/dest_repo_exists_not_directory.sh && tests/dest_repo_exists_not_git_repo.sh && tests/dest_repo_exists.sh"
