version: 1.0.{build}

install:
  - ps: C:\cygwin\setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P bash -P grep

build_script:
  - ps: bash tests/test.sh